# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AskGenie < Formula
  desc "CLI app to suggest prompted commands"
  homepage "https://github.com/the-Jinxist/cmd_genie"
  version "0.4.5"

  on_macos do
    on_intel do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.5/cmd_genie_Darwin_x86_64.tar.gz"
      sha256 "3917447e44a88c4d385f8915ffbf76133069a7d8eeec645cb8b437086200b2e9"

      def install
        bin.install "cmd_genie"
      end
    end
    on_arm do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.5/cmd_genie_Darwin_arm64.tar.gz"
      sha256 "ca7c9861dc801a30b9d81aa375ebfbdec545c92a8e8c74373ec182d8d526ab72"

      def install
        bin.install "cmd_genie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.5/cmd_genie_Linux_x86_64.tar.gz"
        sha256 "e80fcea0aad498658ccfca05749d24dc845318dc2eebd52c7875b4d711ddb5f8"

        def install
          bin.install "cmd_genie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.4.5/cmd_genie_Linux_arm64.tar.gz"
        sha256 "36793c4d21f5db6bf1b323595726af2c25a0f8106672489f4d029c9ef2ed2d03"

        def install
          bin.install "cmd_genie"
        end
      end
    end
  end

  def post_install
    cmd_genie --help
  end
end
