# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AskGenie < Formula
  desc "CLI app to suggest prompted commands"
  homepage "https://github.com/the-Jinxist/cmd_genie"
  version "0.5.3"

  on_macos do
    on_intel do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.5.3/cmd_genie_Darwin_x86_64.tar.gz"
      sha256 "833d56bfde6ec59c580d35e2b3413fd7d57ed04ef2b69da4bfe1364dc6c3abda"

      def install
        bin.install "cmd_genie"
      end
    end
    on_arm do
      url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.5.3/cmd_genie_Darwin_arm64.tar.gz"
      sha256 "e923593285a93e1a1a896c810ae000f5d419dbe2dc88846cc34de35e7061f24d"

      def install
        bin.install "cmd_genie"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.5.3/cmd_genie_Linux_x86_64.tar.gz"
        sha256 "1d4a918e96766c6726a915d01f2f4bded5624976312cb7516f999b57582b5b93"

        def install
          bin.install "cmd_genie"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/cmd_genie/releases/download/v0.5.3/cmd_genie_Linux_arm64.tar.gz"
        sha256 "db786989399972cb95ae1dc16ea49cc53a797739c9faef1ca686799d5c58a648"

        def install
          bin.install "cmd_genie"
        end
      end
    end
  end

  def post_install
    cmd_genie --help
  end
end
